{
 "title": "dsrv-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m) \n  |> filter(fn: (r) => \n      r._measurement == \"node_metrics\")\n  |> keep(columns: [\"nodeAddress\"])\n  |> distinct(column: \"nodeAddress\")\n"
    }
   ]
  },
  {
   "title": "Role",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => \n      r._measurement == \"node_metrics\")\n  |> group()\n  |> last() \n  |> keep(columns: [\"role\"])  \n"
    }
   ]
  },
  { "title": "General stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total reward",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"node_metrics\")\n  |> filter(fn: (r) => r._field == \"reward\")\n  |> sum()\n  |> group()\n  |> keep(columns: [\"_value\"])\n  |> rename(columns: {_value: \"total_reward\"})\n  |> yield(name: \"total_reward\")"
    }
   ]
  },
  {
   "title": "Last block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"node_metrics\")\n  |> filter(fn: (r) => r._field == \"blockHeight\")\n  |> last()\n  |> group()\n  |> yield(name: \"last_blockHeight\")"
    }
   ]
  },
  {
   "title": "Total submitted blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"node_metrics\")\n  |> filter(fn: (r) => r.status == \"success\")\n  |> group()\n  |> count()\n  |> yield(name: \"total_true_status\")\n"
    }
   ]
  },
  {
   "title": "Total failed blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"node_metrics\")\n  |> filter(fn: (r) => r.status == \"fail\")\n  |> group()\n  |> count()\n  |> yield(name: \"total_true_status\")\n"
    }
   ]
  },
  { "title": "AVS table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Complete table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"nodeAddress\"] == \"0xAAA64BFBB7b2EE431d873d9A6302d9c9e5B22a55\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group(columns: [\"_time\", \"_start\", \"_stop\", \"host\", \"leaderAddress\", \"nodeAddress\", \"role\", \"status\"], mode: \"except\")\n  |> pivot(\n    rowKey:[\"_time\", \"leaderAddress\", \"role\", \"status\"], \n    columnKey: [\"_field\"], \n    valueColumn: \"_value\"\n) |> sort(columns: [\"_time\"], desc: true)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "reward = f(time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_metrics\")\n  |> group()\n  |> filter(fn: (r) => r[\"_field\"] == \"reward\")\n"
    }
   ]
  },
  {
   "title": "block=f(time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"avs-dashboard\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_metrics\")\n  |> group()\n  |> filter(fn: (r) => r[\"_field\"] == \"blockHeight\")\n"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } }
 ]
}